name: aku_community_manager
description: A new Flutter application.

publish_to: "none" 

version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  #屏幕适配
  flutter_screenutil: ^3.2.0
  #状态管理
  provider: ^4.3.2+2
  #路由
  get: ^3.15.0
  #刷新
  flutter_easyrefresh: ^2.1.6
  #划动组件
  carousel_slider: ^2.3.1
  #qrcode san
  qr_code_scanner: ^0.3.4
  #toast
  bot_toast: ^3.0.4

  extended_text: ^4.0.0

  common_utils: ^1.2.1
  #验证码
  pin_input_text_field: ^3.1.1

  image_picker: ^0.6.7+12

  flutter_rating_bar: ^3.0.1+1

  expandable: ^4.1.4

  url_launcher: ^5.7.10

  amap_map_fluttify: ^0.29.0

  permission_handler: ^5.0.1+1

  dio:

  power_logger:
    git:
      url: http://192.168.2.201:8099/aku_fe/power_logger.git
  logger: ^0.9.4
  aku_ui:
    git:
      url: http://test.akuhotel.com:8099/aku_fe/aku_ui.git

  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  jpush_flutter: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/home/
    - assets/user/
    - assets/message/
    - assets/manage/
    - assets/inspection/
    - assets/outdoor/

    - assets/static_temp/
    - assets/static_fix/

  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf

