name: aku_new_community_manager
description: A new Flutter application.

publish_to: "none"

version: 1.8.5-dev+19

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  #屏幕适配
  flutter_screenutil: ^5.0.0-nullsafety.11
  #状态管理
  provider: ^5.0.0
  #路由
  get: ^4.0.0-nullsafety.2
  #刷新
  flutter_easyrefresh: ^2.1.6
  #划动组件
  carousel_slider: ^4.0.0-nullsafety.0
  #qrcode san
  qr_code_scanner: ^0.4.0-nullsafety.0
  #toast
  bot_toast: ^4.0.1
  #websocket
  web_socket_channel: ^2.1.0
  #文件路径
  path_provider: ^2.0.1

  extended_text: ^5.0.4

  common_utils: ^2.0.2
  #验证码
  pin_input_text_field: ^4.0.0

  image_picker: ^0.7.4

  flutter_rating_bar: ^4.0.0

  expandable: ^5.0.1

  url_launcher: ^6.0.3
  amap_flutter_map: ^2.0.1
  amap_flutter_location: ^2.0.0
  amap_flutter_base: ^2.0.0
  permission_handler: ^6.1.1

  velocity_x: ^2.6.0
  dotted_border: ^2.0.0-nullsafety.0
  dio: ^4.0.0
#  #谷歌崩溃分析
#  firebase_core: ^1.0.3
#  firebase_crashlytics: ^2.0.0
  #瀑布流
  waterfall_flow: ^3.0.1

  power_logger: ^1.2.1
  logger: ^1.0.0

  hive: ^2.0.4
  hive_flutter: ^1.0.0
  jpush_flutter:
    git:
      url: https://git.oa00.com/flutter_third/jpush-flutter-plugin

  shimmer: ^2.0.0-nullsafety.0
  badges: ^2.0.0-nullsafety.1
  json_annotation: ^4.0.1
  equatable: ^2.0.0
  #打开文件
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.5.1
  hive_generator: ^1.1.0
  grinder: ^0.9.0
  #json序列化
  json_serializable: ^6.1.3
  build_runner: ^2.0.3
  yaml: ^3.1.0
  pub_semver: ^2.0.0
  flutter_gen_runner: ^4.1.3
  #验证码自动填充
  sms_autofill: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/home/
    - assets/user/
    - assets/message/
    - assets/manage/
    - assets/inspection/
    - assets/outdoor/

    - assets/static_temp/
    - assets/static_fix/
  generate: true
  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
